version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"