version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"

version: "3.7"
services:
  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"

 artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.11.0
    network_mode: "host"
    environment: 
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin