CREATE TABLE prato (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(200) NULL,
	nome varchar(50) NULL,
	preco numeric(19,2) NOT NULL,
	restaurante_id int8 NOT NULL
);

ALTER TABLE prato ADD CONSTRAINT prato_restaurante
FOREIGN KEY (restaurante_id) REFERENCES restaurante(id);