CREATE TABLE restaurante (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(50) NULL,
	localizacao_id int8 NOT NULL,
	CONSTRAINT restaurante_pk PRIMARY KEY (id)
);

ALTER TABLE restaurante ADD CONSTRAINT restaurante_localizacao
 FOREIGN KEY (localizacao_id) REFERENCES localizacao(id);